name: 'Aditi '
favicon: null
layout_spectrum: 0.33403878356330097
typography_spectrum: 0.7159340272191912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25794043648056686
  lightness: 0.7572755347937346
  saturation: 0.5261643817648292
  rhythmicContrast: 0.7571051567792892
purpose: []
